### ISSUE TITLE
Request for Code, Dataset, and Results for Reproduction

### ISSUE THREAD

**Issue by BodaFu** [Jinpeng-Yu/GeoFormer#1]
Hello

I would like to express my appreciation for your excellent work on the paper. I have read it with great interest and found the ideas and findings very valuable for my own research/study.

I am currently trying to better understand your approach and would like to reproduce the results presented in the paper. However, I noticed that the repository currently does not contain the code, dataset, or detailed results. I was wondering if it would be possible for you to upload these resources, or perhaps provide guidance on how to access them.

I believe that having access to these materials would be incredibly helpful for the community and for anyone who wants to dive deeper into your research.

Thank you very much for your time and consideration. I look forward to hearing from you.

**Comment by Jinpeng-Yu** [comment]
Hi XDUchpn,

Thanks for your interest in our work. I am actively working on organizing and refining the open-source code and related resources. There are still some aspects that still need to be finalized to ensure they are as clear as possible. Thank you for your patience and understanding. I will notify you as soon as the resources are available.

**Comment by Jinpeng-Yu** [comment]
Thank you for your patience, we have released the relevant code and pre-trained models
