### ISSUE TITLE
License of Code

### ISSUE THREAD

**Issue by goldragoon** [Jinpeng-Yu/GeoFormer#4]
Thanks for wonderful research and code!
what is the license of this repository?

**Comment by Jinpeng-Yu** [comment]
Our project is licensed under the MIT License. We hope that our work proves to be useful in your endeavors. If you find our project helpful and you use it in your own research or applications, we would greatly appreciate it if you could cite our work.

**Comment by goldragoon** [comment]
Thanks for fast reply.
I will!
